//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDSK.QuiqCompose.WinDesktop.Translations {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SDSK.QuiqCompose.WinDesktop.Translations.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Dependencies과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppInfoWindow_OSL_ShowDepsText {
            get {
                return ResourceManager.GetString("AppInfoWindow_OSL_ShowDepsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Source Libraries과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppInfoWindow_OSLTab_Header {
            get {
                return ResourceManager.GetString("AppInfoWindow_OSLTab_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Overview과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppInfoWindow_OverviewTab_Header {
            get {
                return ResourceManager.GetString("AppInfoWindow_OverviewTab_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version v{0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppInfoWindow_VersionFormat {
            get {
                return ResourceManager.GetString("AppInfoWindow_VersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Media과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ComposeSubWindow_Media_Title {
            get {
                return ResourceManager.GetString("ComposeSubWindow_Media_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show the list of accounts과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ComposeWindow_AccountList_ToolTip {
            get {
                return ResourceManager.GetString("ComposeWindow_AccountList_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add an account과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ComposeWindow_AddAccount_ToolTip {
            get {
                return ResourceManager.GetString("ComposeWindow_AddAccount_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Program informations과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ComposeWindow_AppInfo_ToolTip {
            get {
                return ResourceManager.GetString("ComposeWindow_AppInfo_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open profile page with a browser과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ComposeWindow_OpenAccountWithBrowser_ToolTip {
            get {
                return ResourceManager.GetString("ComposeWindow_OpenAccountWithBrowser_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This will remove the account from the list.
        ///※ You should re-authenticate if you want to add the account again. Continue?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ComposeWindow_RemoveAccount_Message {
            get {
                return ResourceManager.GetString("ComposeWindow_RemoveAccount_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ComposeWindow_Send_ToolTip {
            get {
                return ResourceManager.GetString("ComposeWindow_Send_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please add an account!
        ///Account can be added by pressing plus(+) button above.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ComposeWindow_TextBox_Hint_AddAccount {
            get {
                return ResourceManager.GetString("ComposeWindow_TextBox_Hint_AddAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   What are you doing now?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ComposeWindow_TextBox_Hint1 {
            get {
                return ResourceManager.GetString("ComposeWindow_TextBox_Hint1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   What&apos;s happening now?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ComposeWindow_TextBox_Hint2 {
            get {
                return ResourceManager.GetString("ComposeWindow_TextBox_Hint2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   What are you thinking now?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ComposeWindow_TextBox_Hint3 {
            get {
                return ResourceManager.GetString("ComposeWindow_TextBox_Hint3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   What do you want to say now?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ComposeWindow_TextBox_Hint4 {
            get {
                return ResourceManager.GetString("ComposeWindow_TextBox_Hint4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   How are you feeling now?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ComposeWindow_TextBox_Hint5 {
            get {
                return ResourceManager.GetString("ComposeWindow_TextBox_Hint5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl+Enter : Quick send
        ///Ctrl+Mouse Wheel : Zoom in/out the text size과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ComposeWindow_TextBox_ShortcutsToolTip {
            get {
                return ResourceManager.GetString("ComposeWindow_TextBox_ShortcutsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Global_Cancel {
            get {
                return ResourceManager.GetString("Global_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Global_Close {
            get {
                return ResourceManager.GetString("Global_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Global_Download {
            get {
                return ResourceManager.GetString("Global_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Homepage과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Global_Homepage {
            get {
                return ResourceManager.GetString("Global_Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Global_No {
            get {
                return ResourceManager.GetString("Global_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Global_OK {
            get {
                return ResourceManager.GetString("Global_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   QuiqCompose과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Global_ProgramName {
            get {
                return ResourceManager.GetString("Global_ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Global_Settings {
            get {
                return ResourceManager.GetString("Global_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Global_Warning {
            get {
                return ResourceManager.GetString("Global_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yes과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Global_Yes {
            get {
                return ResourceManager.GetString("Global_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The configuration file is invalid. It should be re-created, but the configurations you made before will be gone.
        ///If you don&apos;t allow to re-create it, QuiqCompose will malfunction.
        ///
        ///Continue to re-create it?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PreparationWindow_Ask_RecreateConfigurationFile {
            get {
                return ResourceManager.GetString("PreparationWindow_Ask_RecreateConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Checking for Internet connection...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PreparationWindow_Status_CheckForInternetConnection {
            get {
                return ResourceManager.GetString("PreparationWindow_Status_CheckForInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to check Internet connection.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PreparationWindow_Status_CheckForInternetConnection_Failed {
            get {
                return ResourceManager.GetString("PreparationWindow_Status_CheckForInternetConnection_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Starting check for updates...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PreparationWindow_Status_CheckForUpdate {
            get {
                return ResourceManager.GetString("PreparationWindow_Status_CheckForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading configurations...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PreparationWindow_Status_LoadConfigurations {
            get {
                return ResourceManager.GetString("PreparationWindow_Status_LoadConfigurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Updating account information...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PreparationWindow_Status_UpdateAccountInfo {
            get {
                return ResourceManager.GetString("PreparationWindow_Status_UpdateAccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsWindow_BottomBar_Reset {
            get {
                return ResourceManager.GetString("SettingsWindow_BottomBar_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you really want to reset the settings?
        ///If you select Yes, the settings except account informations will be reset and the application will be restarted.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsWindow_BottomBar_Reset_Message {
            get {
                return ResourceManager.GetString("SettingsWindow_BottomBar_Reset_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check for updates on application startup과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsWindow_General_CheckUpdatesOnStartup {
            get {
                return ResourceManager.GetString("SettingsWindow_General_CheckUpdatesOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsWindow_General_Languages {
            get {
                return ResourceManager.GetString("SettingsWindow_General_Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Top Most과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsWindow_General_TopMost {
            get {
                return ResourceManager.GetString("SettingsWindow_General_TopMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsWindow_GeneralTab_Header {
            get {
                return ResourceManager.GetString("SettingsWindow_GeneralTab_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send to the server how many the tweet has been composed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsWindow_Privacy_ReportTweetCount {
            get {
                return ResourceManager.GetString("SettingsWindow_Privacy_ReportTweetCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ONLY the tweet count how many you composed will be sent.
        ///This information will be used for analytical purpose and to show the total count of composed tweet through this application on the homepage.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsWindow_Privacy_ReportTweetCount_Hint {
            get {
                return ResourceManager.GetString("SettingsWindow_Privacy_ReportTweetCount_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This setting would not gather the user&apos;s personal information anyway so this setting is permanently enabled.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsWindow_Privacy_ReportTweetCount_PermanentToolTip {
            get {
                return ResourceManager.GetString("SettingsWindow_Privacy_ReportTweetCount_PermanentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Privacy과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsWindow_PrivacyTab_Header {
            get {
                return ResourceManager.GetString("SettingsWindow_PrivacyTab_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open the profile page on click the account from compose window과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsWindow_Ui_OpenProfilePageOnAccountClick {
            get {
                return ResourceManager.GetString("SettingsWindow_Ui_OpenProfilePageOnAccountClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keep last selected account position과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsWindow_Ui_SaveLastAccountPosition {
            get {
                return ResourceManager.GetString("SettingsWindow_Ui_SaveLastAccountPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show account profile image과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsWindow_Ui_ShowProfileImage {
            get {
                return ResourceManager.GetString("SettingsWindow_Ui_ShowProfileImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Appearance과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsWindow_UiTab_Header {
            get {
                return ResourceManager.GetString("SettingsWindow_UiTab_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Re-open authentication page과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TwitterLoginWindow_Commands_Reload {
            get {
                return ResourceManager.GetString("TwitterLoginWindow_Commands_Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The account is already authenticated before. This will refresh the account information.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TwitterLoginWindow_Messages_AuthedBefore {
            get {
                return ResourceManager.GetString("TwitterLoginWindow_Messages_AuthedBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to make authentication. Please retry.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TwitterLoginWindow_Messages_Failed {
            get {
                return ResourceManager.GetString("TwitterLoginWindow_Messages_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter 7-digit PIN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TwitterLoginWindow_Pin_Hint {
            get {
                return ResourceManager.GetString("TwitterLoginWindow_Pin_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BETA RELEASE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UpdateFoundWindow_Channel_Beta {
            get {
                return ResourceManager.GetString("UpdateFoundWindow_Channel_Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Official release과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UpdateFoundWindow_Channel_Official {
            get {
                return ResourceManager.GetString("UpdateFoundWindow_Channel_Official", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TESTING RELEASE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UpdateFoundWindow_Channel_Testing {
            get {
                return ResourceManager.GetString("UpdateFoundWindow_Channel_Testing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unspecified channel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UpdateFoundWindow_Channel_Unspecified {
            get {
                return ResourceManager.GetString("UpdateFoundWindow_Channel_Unspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current version is v{0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UpdateFoundWindow_CurrentVer {
            get {
                return ResourceManager.GetString("UpdateFoundWindow_CurrentVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A new version is ready to go!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UpdateFoundWindow_FoundText {
            get {
                return ResourceManager.GetString("UpdateFoundWindow_FoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version v{0}, released on {1}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UpdateFoundWindow_NewVerAndDate {
            get {
                return ResourceManager.GetString("UpdateFoundWindow_NewVerAndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View changelog과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UpdateFoundWindow_ViewChangelog {
            get {
                return ResourceManager.GetString("UpdateFoundWindow_ViewChangelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The changelog URL seems wrong, or not provided. please contact to developer.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UpdateFoundWindow_WrongChangelogUrl {
            get {
                return ResourceManager.GetString("UpdateFoundWindow_WrongChangelogUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The download URL seems wrong, please contact to developer.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UpdateFoundWindow_WrongDownloadUrl {
            get {
                return ResourceManager.GetString("UpdateFoundWindow_WrongDownloadUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Application information과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WindowTitle_AppInfo {
            get {
                return ResourceManager.GetString("WindowTitle_AppInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compose과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WindowTitle_Compose {
            get {
                return ResourceManager.GetString("WindowTitle_Compose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preparing...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WindowTitle_Preparation {
            get {
                return ResourceManager.GetString("WindowTitle_Preparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WindowTitle_Settings {
            get {
                return ResourceManager.GetString("WindowTitle_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Twitter authentication과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WindowTitle_TwitterLogin {
            get {
                return ResourceManager.GetString("WindowTitle_TwitterLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A new version found!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WindowTitle_UpdateFound {
            get {
                return ResourceManager.GetString("WindowTitle_UpdateFound", resourceCulture);
            }
        }
    }
}
